### ISSUE TITLE
XCode Project Broken

### ISSUE THREAD

**Issue by gmacd** [zaphire/Monocle-Engine#101]
The Xcode project is broken.  It references lua files that don't exist in the repository.

**Comment by soundofjw** [comment]
I'll fix this pronto when I get back to the house tonight.

**Comment by gmacd** [comment]
Noticed the tests have broken refs too :-)

**Comment by zaphire** [comment]
Premake4 beta can build Xcode4 project files that work (For me at least)

you can run this on the "development" branch and it should work

**Comment by soundofjw** [comment]
Yes, this completely threw me off when I first read it. premake4 should work wonderfully. Don't rely on the preincluded project files.

**Comment by gmacd** [comment]
Ok, I'll do that, but unless you want this to become a recurring problem, it needs to be kept up to date, or replaced with a very explicitly named script that will run premake for the user.

**Comment by soundofjw** [comment]
Unless I'm mistaken, premake4 is the only way we're encouraging builds on any system. It's much like CMAKE with other projects. The best solution, I believe, would be to remove the xcode project from git altogether.

**Comment by zaphire** [comment]
I think what would be most convenient is if we could somehow automate premake4 to build new project files when we push to master.

This would be the nicest option for new folks who just want to try out the engine, I think.

I don't know if such automation is possible, but I suppose it could be as simple as a batch file that we have to remember to run before pushing to master.

Any other ideas? :)

**Comment by fgenesis** [comment]
To totally automate things try using a git commit hook as described here:
http://www.kernel.org/pub/software/scm/git/docs/githooks.html -- the pre-commit hook is what you're looking for.
When a new file is generated that needs to be added, exit the hook script with nonzero status to abort committing, add the file, and commit again. Or just invoke "git add xyz" from the script, should work as well.
It is a bit of shell hackery, but once it works, put the file into the repo as well and everyone can use it then.
Makes human error less likely too :)

**Comment by gmacd** [comment]
Incidentally, how do you guys build the xcode project?  I'd like to build the engine and the test apps.  I tried 'premake4 --testapp=all xcode4'...  It builds into 'Build/gen-xcode4-all' which doesn't seem right...  right?  (Although it does seem to work)

**Comment by bzgeb** [comment]
I probably should've read this ticket before fixing the the project file.
