### ISSUE TITLE
Is a good idea mantaining input and window managemente at Xlib level?

### ISSUE THREAD

**Issue by lele85** [zaphire/Monocle-Engine#42]
I'm wondering if mantaining the low level platform specific input handling  is a good idea or just a big source of problems. I totally appreciate the control that comes from this kind of independence but at the same time i'm worried about the fact that code is not heavily tested.

I'm asking if you think that some external, well tested lib can do the trick. OIS[0] seems to be a good candidate for this dirty job:
- Multiplatform (win, linux, osx, ios)
- Clean OO interface
- Compact
- Fairly recent
- Liberal Open license (zlib)

I could try to integrate this solution in Monocle Linux platform to explore the possibility, but i'd like to know your point of view first.

Emanuele

[0] Objec Oriented Input System: http://sourceforge.net/projects/wgois/

**Comment by zaphire** [comment]
I'd rather not use a library if we can avoid it, so we can have more control and have more flexibility when it comes to porting to new platforms.

If enough people end up using the engine, I think we'll be able to isolate and test platform issues fairly quickly as they come up. So far it seems to be working pretty well?

**Comment by lele85** [comment]
In linux there are some problems in the TestOgmo test. Jump height seems to be completely random (i don't know if the bug is in game code but i think that there's some platform specific problem). About my proposition i was just thinking out loud... i totally get your point
I'll investigate the problem sticking to the actual implementation.

**Comment by zaphire** [comment]
My guess would be the timing code on Linux, it seems to behave differently than on other platforms for some reason. :)

**Comment by zaphire** [comment]
i.e. Monocle::deltaTime

**Comment by lele85** [comment]
mmmm I'm not sure... i've just changed and committed the time code for linux platform to reflect the cocoa one and the random jump issue is still here.

**Comment by lele85** [comment]
The problem was in the demo phisics logic... applying deltaTime on velocity pulse makes jump and movements in general frame rate dependant. I'll fix the demo and commit the correct code.

**Comment by zaphire** [comment]
Cool, thanks for the fix. :)
