### ISSUE TITLE
Textures don't alpha-blend on Mac 64-bit (development branch)

### ISSUE THREAD

**Issue by JoeOsborn** [zaphire/Monocle-Engine#71]
See title; things otherwise seem pretty OK on the 64-bit front. I don't know if 64-bit is a priority for you, but it surprised me when I saw the bug: the textures just have white backgrounds where there should be alpha.

**Comment by soundofjw** [comment]
I develop primarily on Mac 64 bit and have not seen this problem. Can you send more details or a screenshot?

**Comment by JoeOsborn** [comment]
The only detail is that I did a fresh 64-bit build in Xcode 4 on Mac OS 10.6. Here's the behavior: http://joe.lt3.us/me_bug.png

**Comment by soundofjw** [comment]
Curious. Are you running through the TestSelector app? Also, any details on your machine?

http://ploader.net/files/f41e8e6547ab2960b43dd6739ee0dcd5.png

**Comment by JoeOsborn** [comment]
Yep, I am. The machine is a 13" MacBook Air without any unusual modifications. Text also shows up as white rectangles (though they are of the appropriate sizes, etc, and render fine in 32-bit mode). I think this is because they're drawing as white-on-alpha, which comes out to white-on-white.

**Comment by soundofjw** [comment]
Hmm - I am on a MacBook Pro myself. 

The only place I can see that it would cause that issue is OpenGL/OpenGLTextureAsset.cpp or stb_image.

The code here is:
unsigned char\* data = stbi_load(filename.c_str(), &w, &h, &n, STBI_rgb_alpha);

If I replace that to STBI_rgb and tell OpenGL it's just an RGB, I can recreate your screenshot. So the alpha channel isn't being loaded properly for you in 64bit... _winces_

**Comment by soundofjw** [comment]
Oh! Wait a minute, did the TestSelector screen render text render, telling you "Press 1 for ..." etc?

**Comment by JoeOsborn** [comment]
It shows as white rectangles of varying sizes -- white on alpha, thus white on white.

Could it have to do with the switch statement at OpenGLCraphics.cpp:88? It's missing a case for BLEND_NONE. A long shot, I guess. Or could it have to do with some ignored 64-bit size/precision/signedness warnings?

**Comment by soundofjw** [comment]
Oh, there we go.

**REPRODUCE**: Build as Release configuration and run on XCode4. (You can do this quickly by attempting to profile)

**Comment by soundofjw** [comment]
Fixed with commit 73cabbbd486b08deb301

**Comment by JoeOsborn** [comment]
Awesome! Just wanted to let you know this fix worked a trick for me as well. Good detective work!
