### ISSUE TITLE
KEY_QUOTE doesn't work as expected

### ISSUE THREAD

**Issue by etinquis** [zaphire/Monocle-Engine#76]
I expected KEY_QUOTE to be the ' character on the keyboard, but that is incorrect in my case.  The linux platform implementation binds XK_quotedbl to that key, but the value that works for ' is XK_apostrophe.

**Comment by etinquis** [comment]
I have a change that fixes it for me on my fork (https://github.com/etinquis/Monocle-Engine/commit/409ff7095f7b67164ee23318f5dcc3d9705ea2d6).  I left the KEY_QUOTE in because I didn't know if it was intended to do something else.

Edit: Didn't mean to close it.

**Comment by zaphire** [comment]
Merged your changes for now. Not really sure if Quote should be single or what yet.
