### ISSUE TITLE
Platform init changes break tests

### ISSUE THREAD

**Issue by etinquis** [zaphire/Monocle-Engine#82]
I'm using nvidia's linux driver which reports my monitors as having a color depth of 24, which means the new default of 32 in the Game class can't find a compatible display from glXChooseVisual.  Does a default of 24 break the Windows init, and if not, can the default be set to 24?

**Comment by zaphire** [comment]
Let's try it...

**Comment by zaphire** [comment]
K pushed 24 bits as default, I'll close this for now. If we run into problems with creating the window / graphics, it might be something to do with this.
